## ╔════════════════════════════════════════════════╗
## ║ Ini: Initialisation File Nearest Neighbour App ║
## ╚════════════════════════════════════════════════╝

[filenames]
# Detailed data
practice_data_filename=df_practice_data.csv
pcn_data_filename=df_pcn_data.csv
# Top 10 matches
practice_top10_filename=df_top10_practices.csv
pcn_top10_filename=df_top10_pcn.csv
# Metadata
practice_metadata_filename=practice_data_metadata.csv
pcn_metadata_filename=pcn_data_metadata.csv



